### ISSUE TITLE
Installation failure on VSCode 17.9

### ISSUE THREAD

**Issue by TrebucheterChris** [BroadcomMFD/rexx-language-support#17]
Hi,   I just installed the current version of VSCode on windows 11.   I can't install your REXX Language Support extension.  I get the following Log.  
3/15/2024 5:34:09 PM - Microsoft VSIX Installer
3/15/2024 5:34:09 PM - -------------------------------------------
3/15/2024 5:34:09 PM - vsixinstaller.exe version:
3/15/2024 5:34:09 PM - 17.9.3180+083a582996
3/15/2024 5:34:09 PM - -------------------------------------------
3/15/2024 5:34:09 PM - Command line parameters:
3/15/2024 5:34:09 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\cgero\Downloads\broadcomMFD.opsrexx-language-support-0.4.0(1).vsix
3/15/2024 5:34:09 PM - -------------------------------------------
3/15/2024 5:34:09 PM - Microsoft VSIX Installer
3/15/2024 5:34:09 PM - -------------------------------------------
3/15/2024 5:34:09 PM - Initializing Install...
3/15/2024 5:34:09 PM - Searching for applicable products...
3/15/2024 5:34:10 PM - Found installed product - Visual Studio Community 2022
3/15/2024 5:34:10 PM - Found installed product - Global Location
3/15/2024 5:34:10 PM - Extension Details...
3/15/2024 5:34:10 PM - 	Identifier         : opsrexx-language-support
3/15/2024 5:34:10 PM - 	Name               : OPS/REXX Language Support
3/15/2024 5:34:10 PM - 	Author             : broadcomMFD
3/15/2024 5:34:10 PM - 	Version            : 0.4.0
3/15/2024 5:34:10 PM - 	Description        : OPS/REXX Language Support Visual Studio Code Extension
3/15/2024 5:34:10 PM - 	Locale             : en-US
3/15/2024 5:34:10 PM - 	MoreInfoURL        : 
3/15/2024 5:34:10 PM - 	InstalledByMSI     : False
3/15/2024 5:34:10 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
3/15/2024 5:34:10 PM - 	SignatureState     : Unsigned
3/15/2024 5:34:10 PM - 	Supported Products : 
3/15/2024 5:34:10 PM - 		Microsoft.VisualStudio.Code
3/15/2024 5:34:10 PM - 			Version : 
3/15/2024 5:34:10 PM - 			ProductArchitecture : x86
3/15/2024 5:34:10 PM - 	References         : 
3/15/2024 5:34:10 PM - Signature Details...
3/15/2024 5:34:10 PM - 	Extension is not signed.
3/15/2024 5:34:10 PM - VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by zimlu02** [comment]
Hello, 
you have opened a [similar ticket](https://github.com/BroadcomMFD/opsrexx-language-support/issues/1) for OPS/REXX extension. This log still refers to OPS/REXX Language Support - can you confirm you experienced the same for REXX extension and provide the logs, please?
Thank you

**Comment by CraigFreiwald** [comment]
Hello,
It appears you are trying to install this [VS Code](https://code.visualstudio.com/) extension in [Microsoft Visual Studio](https://visualstudio.microsoft.com/).

Please try installing the downloaded .vsix file from within VS Code, or use the VS Code extension marketplace to search for and [install the extension](https://code.visualstudio.com/docs/editor/extension-marketplace).

**Comment by petr-galik** [comment]
This version of VS Code is no longer supported by Microsoft. Please upgrade.
